name: erlang ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp: [25, 26]

    name: OTP ${{ matrix.otp }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Erlang/OTP
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          rebar3-version: '3.23.0'

      - name: Compile
        run: rebar3 compile

      - name: Run tests
        run: rebar3 eunit